# __PROJECT_NAME__

Editable Payload CMS + Next.js migration of __SOURCE_URL__, generated by the
FocusReactive migration tool.

## Commands

- `pnpm dev` — dev server (admin at `/admin`)
- `pnpm build` / `pnpm start` — production build and serve
- `pnpm payload migrate` — apply DB migrations (Postgres, `DATABASE_URI`)
- `pnpm seed` — one-time content seed from the migration workspace
  (requires the `.migration/` working directory of the tool; already executed
  during generation)
- `pnpm lint`, `pnpm generate:types`, `pnpm generate:importmap`

## Notes

- Admin credentials are in `.env` (`PAYLOAD_ADMIN_EMAIL` / `PAYLOAD_ADMIN_PASSWORD`) — rotate them.
- `migration/` holds provenance (`manifest.json`), the structural IR copy and
  `REVIEW.md` (open verification items). `.vercelignore` keeps both migration
  folders out of deploys.
- Source locales were not migrated (single-locale v1); `localized` field flags
  from the source CMS are intentionally ignored.
